83 atualizacao documento de arquitetura
fga-eps-mds/2021.1-Multilind-Docs pull request #119
Opened 2021-09-09 19:09 UTC by pedroeagle

## Descrição

Foi feita a atualização do documento de arquitetura com base nas definições discutidas pelo grupo para a arquitetura do projeto utilizando micro serviços.
## Solução

Foram criados novos diagramas que representam a arquitetura discutida de forma coerente.

## Issue 
Resolve #83 

## Tarefas
- [x] Atualizar diagramas

## Critérios de aceitação 
- [x]  Estar documentado na Wiki

2021-09-10 13:05 UTC, micaellagouveia requested changes

2021-09-10 13:05 UTC, micaellagouveia commented on docs/Project/docArquitetura.md
> +| 09/09/2021 | 1.7 | Atualização do Tópico 2 - Tecnoloias | Pedro Igor |
Tecnologias tá escrito errado

2021-09-10 13:05 UTC, micaellagouveia commented on docs/Project/docArquitetura.md
> +  Para funcionalidades de avaliação de conteúdos inseridos será utilizada a mesma arquitetura no entanto o React Native será substituído pelo React para criação de uma página web onde o usuário admin
Essa página web foi validada pelas clientes?

2021-09-10 13:05 UTC, micaellagouveia commented on docs/Project/docArquitetura.md
> +  Servidor responsável por gerenciar as entidades de usuário do sistea. Este módulo se comunica com o MongoDB.
Sistema ta escrito errado

2021-09-10 15:47 UTC, pedroeagle commented on docs/Project/docArquitetura.md
> +  Para funcionalidades de avaliação de conteúdos inseridos será utilizada a mesma arquitetura no entanto o React Native será substituído pelo React para criação de uma página web onde o usuário admin
Nem passamos pra elas ainda

2021-09-10 17:36 UTC, micaellagouveia approved these changes

2021-09-11 12:18 UTC, sofiapatrocinio requested changes

2021-09-11 12:18 UTC, sofiapatrocinio commented on docs/Project/docArquitetura.md
> +Este documento tem como finalidade fornecer uma visão geral da arquitetura do projeto Línguas Indígenas, utilizando-se de diversas visões arquiteturais, como a visão lógica, a fim de facilitar o ente
Troca o nome do projeto pra Multilind

2021-09-13 11:47 UTC, GabrielDVpereira approved these changes

2021-09-13 11:55 UTC, sofiapatrocinio approved these changes

2021-09-13 11:55 UTC, merged