Planejar S13
fga-eps-mds/2021.1-Multilind-Docs pull request #177
Opened 2021-11-01 13:22 UTC by micaellagouveia

## Descrição

Planejamento s13  e resultados s12

## Solução
Documentação na Wiki

## Issue 
Resolve #174

2021-11-01 13:24 UTC, pedroeagle approved these changes

2021-11-02 02:50 UTC, sofiapatrocinio requested changes

2021-11-02 02:50 UTC, sofiapatrocinio commented on docs/Sprints/results/sprint12.md
> +| [**#90**](https://github.com/fga-eps-mds/2021.1-Multilind-Docs/issues/90) | US02 Avaliação de conteúdos Parte 2 | 8 | MDS | Carlos Rafael e Hérick |
Essa issue foi mergeeada no domingo, não?

2021-11-02 02:50 UTC, sofiapatrocinio commented on docs/Sprints/planning/sprint13.md
> +| [**#176**](https://github.com/fga-eps-mds/2021.1-Multilind-Docs/issues/176) | Apresentação Entrega Final | Sem | EPS + MDS | Todos |
Pode adicionar a issue 188 de melhoria de usabilidade?

2021-11-03 22:53 UTC, micaellagouveia commented on docs/Sprints/results/sprint12.md
> +| [**#90**](https://github.com/fga-eps-mds/2021.1-Multilind-Docs/issues/90) | US02 Avaliação de conteúdos Parte 2 | 8 | MDS | Carlos Rafael e Hérick |
Essa é a parte 2, a parte 1 foi fechada

2021-11-03 23:12 UTC, sofiapatrocinio approved these changes

2021-11-03 23:12 UTC, merged