Requisitos e Priorização
fga-eps-mds/2021.1-Multilind-Docs pull request #75
Opened 2021-09-02 20:39 UTC by micaellagouveia

## Descrição
Adição dos requisitos elencados com sua priorização

## Solução
Documentação escrita no docsify para ser mostrada no GitHub Pages

## Issue 
Closes #34  

## Tarefas
- [x] Elicitação
- [x ] Priorização
- [x] Documentação

2021-09-02 21:13 UTC, sofiapatrocinio requested changes

2021-09-02 21:13 UTC, sofiapatrocinio commented on docs/Produto/requisitos.md
> +4. Wouldn’t (Não será feito (por enquanto))
Aqui é would have, voltaremos a falar em etapas posteriores

2021-09-02 23:45 UTC, micaellagouveia commented on docs/Produto/requisitos.md
> +4. Wouldn’t (Não será feito (por enquanto))
Vc tem uma sugestão da tradução?

2021-09-03 21:33 UTC, pedroeagle approved these changes

2021-09-03 21:35 UTC, sofiapatrocinio approved these changes

2021-09-03 21:35 UTC, merged